apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  name: my-custom-jenkins-agent
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - cat
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker/
  - name: k8s
    image: alpine/k8s:1.24.15
    command:
    - cat
    tty: true
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
      - key: .dockerconfigjson
        path: config.json